name: login_firebase_1
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  tuple: ^1.0.3
  cloud_firestore: ^2.2.0
  flutter_bloc: ^7.0.0
  firebase_auth: ^1.2.0
  firebase_core: ^1.2.0
  equatable: ^2.0.0
  hydrated_bloc: ^7.0.0
  path_provider: ^2.0.1
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.21.0+1
  multiple_stream_builder: ^1.0.0
  shared_preferences: ^2.0.5
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  json_annotation: ^3.1.1
  charts_flutter: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.9
  json_serializable: ^3.5.1
  flutter_launcher_icons: "^0.9.0"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
